/**
 * IPC Channel definitions
 * Main-Renderer 간 통신 채널 정의
 */
export const CHANNELS = {
  // App
  GET_APP_VERSION: 'GET_APP_VERSION',
  GET_SYSTEM_INFO: 'GET_SYSTEM_INFO',

  // Package
  PACKAGE_LIST: 'PACKAGE_LIST',
  PACKAGE_GET: 'PACKAGE_GET',
  PACKAGE_CREATE: 'PACKAGE_CREATE',
  PACKAGE_UPDATE: 'PACKAGE_UPDATE',
  PACKAGE_DELETE: 'PACKAGE_DELETE',
  PACKAGE_LINK_RESOURCE: 'PACKAGE_LINK_RESOURCE',
  PACKAGE_UNLINK_RESOURCE: 'PACKAGE_UNLINK_RESOURCE',
  PACKAGE_GET_RESOURCES: 'PACKAGE_GET_RESOURCES',

  // Connection
  CONNECTION_LIST: 'CONNECTION_LIST',
  CONNECTION_GET: 'CONNECTION_GET',
  CONNECTION_CREATE: 'CONNECTION_CREATE',
  CONNECTION_UPDATE: 'CONNECTION_UPDATE',
  CONNECTION_DELETE: 'CONNECTION_DELETE',
  CONNECTION_TEST: 'CONNECTION_TEST',
  CONNECTION_GET_PASSWORD: 'CONNECTION_GET_PASSWORD',
  CONNECTION_REORDER: 'CONNECTION_REORDER',
  CONNECTION_TEST_BY_ID: 'CONNECTION_TEST_BY_ID',
  CONNECTION_SET_IGNORED: 'CONNECTION_SET_IGNORED',

  // Diagram
  DIAGRAM_LIST: 'DIAGRAM_LIST',
  DIAGRAM_GET: 'DIAGRAM_GET',
  DIAGRAM_CREATE: 'DIAGRAM_CREATE',
  DIAGRAM_UPDATE: 'DIAGRAM_UPDATE',
  DIAGRAM_DELETE: 'DIAGRAM_DELETE',
  DIAGRAM_UPDATE_META: 'DIAGRAM_UPDATE_META',
  DIAGRAM_GET_LAYOUT: 'DIAGRAM_GET_LAYOUT',
  DIAGRAM_SAVE_LAYOUT: 'DIAGRAM_SAVE_LAYOUT',
  DIAGRAM_CLONE: 'DIAGRAM_CLONE',
  DIAGRAMS_REORDER: 'DIAGRAMS_REORDER',

  // Diagram Versions
  DIAGRAM_VERSION_LIST: 'DIAGRAM_VERSION_LIST',
  DIAGRAM_VERSION_CREATE: 'DIAGRAM_VERSION_CREATE',
  DIAGRAM_VERSION_UPDATE: 'DIAGRAM_VERSION_UPDATE',
  DIAGRAM_VERSION_DELETE: 'DIAGRAM_VERSION_DELETE',
  DIAGRAM_VERSION_RESTORE: 'DIAGRAM_VERSION_RESTORE',
  DIAGRAM_VERSIONS_REORDER: 'DIAGRAM_VERSIONS_REORDER',
  DIAGRAM_VERSION_MOVE: 'DIAGRAM_VERSION_MOVE',
  DIAGRAM_VERSION_COPY: 'DIAGRAM_VERSION_COPY',

  // Migration
  MIGRATION_LIST: 'MIGRATION_LIST',
  MIGRATION_CREATE: 'MIGRATION_CREATE',
  MIGRATION_APPLY: 'MIGRATION_APPLY',
  MIGRATION_DELETE: 'MIGRATION_DELETE',
  MIGRATION_ROLLBACK: 'MIGRATION_ROLLBACK',

  // View Snapshot
  VIEW_SNAPSHOT_LIST: 'VIEW_SNAPSHOT_LIST',
  VIEW_SNAPSHOT_CREATE: 'VIEW_SNAPSHOT_CREATE',
  VIEW_SNAPSHOT_RESTORE: 'VIEW_SNAPSHOT_RESTORE',
  VIEW_SNAPSHOT_DELETE: 'VIEW_SNAPSHOT_DELETE',

  // Diagram Hidden
  DIAGRAM_SET_HIDDEN: 'DIAGRAM_SET_HIDDEN',

  // Schema (Real)
  SCHEMA_FETCH_REAL: 'SCHEMA_FETCH_REAL',
  SCHEMA_SYNC_REAL: 'SCHEMA_SYNC_REAL',

  // Schema Objects Introspection
  SCHEMA_OBJECTS_FETCH: 'SCHEMA_OBJECTS_FETCH',
  SCHEMA_OBJECT_DDL: 'SCHEMA_OBJECT_DDL',

  // Object Browser
  OB_TABLE_STATISTICS: 'OB_TABLE_STATISTICS',
  OB_SQLITE_PRAGMA: 'OB_SQLITE_PRAGMA',
  OB_SQLITE_DB_INFO: 'OB_SQLITE_DB_INFO',

  // Query Safety
  QUERY_CLASSIFY_SAFETY: 'QUERY_CLASSIFY_SAFETY',

  // Changelog
  CHANGELOG_LIST: 'CHANGELOG_LIST',
  CHANGELOG_DELETE: 'CHANGELOG_DELETE',

  // Diff
  SCHEMA_DIFF: 'SCHEMA_DIFF',
  SCHEMA_DIFF_VIRTUAL: 'SCHEMA_DIFF_VIRTUAL',
  SCHEMA_APPLY_REAL_TO_VIRTUAL: 'SCHEMA_APPLY_REAL_TO_VIRTUAL',

  // DDL
  DDL_PARSE: 'DDL_PARSE',
  DDL_GENERATE: 'DDL_GENERATE',

  // Query
  QUERY_EXECUTE: 'QUERY_EXECUTE',
  QUERY_LIST: 'QUERY_LIST',
  QUERY_SAVE: 'QUERY_SAVE',
  QUERY_UPDATE: 'QUERY_UPDATE',
  QUERY_DELETE: 'QUERY_DELETE',
  QUERY_HISTORY_LIST: 'QUERY_HISTORY_LIST',
  QUERY_EXPLAIN_ANALYZE: 'QUERY_EXPLAIN_ANALYZE',

  // Document
  DOCUMENT_LIST: 'DOCUMENT_LIST',
  DOCUMENT_GET: 'DOCUMENT_GET',
  DOCUMENT_CREATE: 'DOCUMENT_CREATE',
  DOCUMENT_UPDATE: 'DOCUMENT_UPDATE',
  DOCUMENT_DELETE: 'DOCUMENT_DELETE',
  DOCUMENT_AUTO_GENERATE: 'DOCUMENT_AUTO_GENERATE',
  DOCUMENT_EXPORT: 'DOCUMENT_EXPORT',

  // Validation
  VALIDATION_RUN: 'VALIDATION_RUN',

  // Validation Suite
  VALIDATION_SUITE_LIST: 'VALIDATION_SUITE_LIST',
  VALIDATION_SUITE_GET: 'VALIDATION_SUITE_GET',
  VALIDATION_SUITE_CREATE: 'VALIDATION_SUITE_CREATE',
  VALIDATION_SUITE_UPDATE: 'VALIDATION_SUITE_UPDATE',
  VALIDATION_SUITE_DELETE: 'VALIDATION_SUITE_DELETE',
  VALIDATION_SUITE_RUN: 'VALIDATION_SUITE_RUN',

  // Mocking
  MOCK_GENERATE: 'MOCK_GENERATE',
  MOCK_EXPORT: 'MOCK_EXPORT',

  // Schema Snapshot
  SCHEMA_SNAPSHOT_LIST: 'SCHEMA_SNAPSHOT_LIST',
  SCHEMA_SNAPSHOT_CREATE: 'SCHEMA_SNAPSHOT_CREATE',
  SCHEMA_SNAPSHOT_GET: 'SCHEMA_SNAPSHOT_GET',
  SCHEMA_SNAPSHOT_DELETE: 'SCHEMA_SNAPSHOT_DELETE',
  SCHEMA_SNAPSHOT_RENAME: 'SCHEMA_SNAPSHOT_RENAME',
  SCHEMA_SNAPSHOT_VALIDATE: 'SCHEMA_SNAPSHOT_VALIDATE',

  // Migration Pack
  MIGRATION_PACK_LIST: 'MIGRATION_PACK_LIST',
  MIGRATION_PACK_CREATE: 'MIGRATION_PACK_CREATE',
  MIGRATION_PACK_GET: 'MIGRATION_PACK_GET',
  MIGRATION_PACK_UPDATE_DML: 'MIGRATION_PACK_UPDATE_DML',
  MIGRATION_PACK_EXECUTE: 'MIGRATION_PACK_EXECUTE',
  MIGRATION_PACK_ROLLBACK: 'MIGRATION_PACK_ROLLBACK',
  MIGRATION_PACK_DELETE: 'MIGRATION_PACK_DELETE',

  // Drift Detection
  DRIFT_LIGHTWEIGHT_CHECK: 'DRIFT_LIGHTWEIGHT_CHECK',
  DRIFT_FULL_CHECK: 'DRIFT_FULL_CHECK',

  // Seed
  SEED_LIST: 'SEED_LIST',
  SEED_CREATE: 'SEED_CREATE',
  SEED_UPDATE: 'SEED_UPDATE',
  SEED_DELETE: 'SEED_DELETE',
  SEED_CAPTURE: 'SEED_CAPTURE',
  SEED_CAPTURE_WITH_FK: 'SEED_CAPTURE_WITH_FK',
  SEED_APPLY: 'SEED_APPLY',

  // Forward (Concurrent Control)
  FORWARD_PRE_CHECK: 'FORWARD_PRE_CHECK',
  FORWARD_EXECUTE_STEP: 'FORWARD_EXECUTE_STEP',
  FORWARD_ROLLBACK: 'FORWARD_ROLLBACK',

  // Mocking Apply
  MOCK_APPLY: 'MOCK_APPLY',

  // Composite
  SCHEMA_VALIDATE_AGAINST_VERSION: 'SCHEMA_VALIDATE_AGAINST_VERSION',

  // Query Browser
  QB_QUERY_TREE_LIST: 'QB_QUERY_TREE_LIST',
  QB_QUERY_FOLDER_SAVE: 'QB_QUERY_FOLDER_SAVE',
  QB_QUERY_FOLDER_DELETE: 'QB_QUERY_FOLDER_DELETE',
  QB_QUERY_SAVE: 'QB_QUERY_SAVE',
  QB_QUERY_GET: 'QB_QUERY_GET',
  QB_QUERY_DELETE: 'QB_QUERY_DELETE',
  QB_QUERY_BULK_MOVE: 'QB_QUERY_BULK_MOVE',
  QB_COLLECTION_TREE_LIST: 'QB_COLLECTION_TREE_LIST',
  QB_COLLECTION_FOLDER_SAVE: 'QB_COLLECTION_FOLDER_SAVE',
  QB_COLLECTION_FOLDER_DELETE: 'QB_COLLECTION_FOLDER_DELETE',
  QB_COLLECTION_SAVE: 'QB_COLLECTION_SAVE',
  QB_COLLECTION_GET: 'QB_COLLECTION_GET',
  QB_COLLECTION_DELETE: 'QB_COLLECTION_DELETE',
  QB_COLLECTION_ITEM_SAVE: 'QB_COLLECTION_ITEM_SAVE',
  QB_TX_BEGIN: 'QB_TX_BEGIN',
  QB_TX_EXECUTE: 'QB_TX_EXECUTE',
  QB_TX_COMMIT: 'QB_TX_COMMIT',
  QB_TX_ROLLBACK: 'QB_TX_ROLLBACK',
  QB_HISTORY_LIST: 'QB_HISTORY_LIST',
  QB_HISTORY_DELETE: 'QB_HISTORY_DELETE',
} as const;

export type TChannelKeys = keyof typeof CHANNELS;
